### ISSUE TITLE
The movie API we're using and guide videos

### ISSUE THREAD

**Issue by Henotis** [yauhofung/MovieSearchEngine#12]
### Our movie API:
* https://www.themoviedb.org/documentation/api
### Some guide videos:
* https://www.youtube.com/watch?v=bqSSLr8A8PU
* https://www.youtube.com/watch?v=o-_H6TdXgiU&list=PL_kAgwZgMfWyZ6m8fDwdiwEarr_g6nFxz

**Comment by rtaverna** [comment]
If you haven't already committed to this one, I would recommend http://www.omdbapi.com/
There's no waiting to be approved for your API key, and Elvis & I have both used it in the past so there should be no surprises

**Comment by yauhofung** [comment]
We took a look at http://www.omdbapi.com/ yesterday when we were deciding on an API to use. I think we ultimately settled on https://www.themoviedb.org/documentation/api because it is very well-documented, and it offers a lot of the functionalities we want to implement for our site.
