### ISSUE TITLE
We were on the hunt for a good command to insert the graphic poster - - 

### ISSUE THREAD

**Issue by SuperArtisMickens** [yauhofung/MovieSearchEngine#14]
This might be it:
this is a possible command to insert the movie posters....

`<img style="border-radius: 50%; box-shadow: 5px 5px 5px yellow; opacity:0.3" src="(insert the webpage graphix here)" alt="(comment in here)" />`
you can change the parameters of course...
* border-radius
* box-shadow
* opacity

this is another command:
`<video src="(website)" poster="(poster_name_site)" controls width"300"></video>`

**Comment by yauhofung** [comment]
Alternatively, we can use Material UI's grid list to display the search results.
https://material-ui.com/components/grid-list/#grid-list-with-titlebars
