### ISSUE TITLE
We need an initial grid layout for the home page for label:

### ISSUE THREAD

**Issue by Henotis** [yauhofung/MovieSearchEngine#18]

**Comment by SuperArtisMickens** [comment]
any ideas?

**Comment by Henotis** [comment]
See grid and grid list for examples: https://material-ui.com/components/grid-list/

**Comment by yauhofung** [comment]
I've already added a Grid to the search form, so keep an eye out for it when I open the pull request.

**Comment by ddesir** [comment]
Homepage for label?
