### ISSUE TITLE
Proposal Election

### ISSUE THREAD

**Issue by yauhofung** [yauhofung/MovieSearchEngine#2]
Let's decide which proposal we want to carry out for our capstone project.
Close this issue once everyone has cast their vote.

**Comment by yauhofung** [comment]
For my vote, I'd like to implement idea two, the movie search engine.

**Comment by ddesir** [comment]
Idea 2 works for me too. Movie search engine.

**Comment by SuperArtisMickens** [comment]
Movie engine search it is !! Let's do it!

**Comment by yauhofung** [comment]
Issue closed: Idea two wins by majority vote.
