### ISSUE TITLE
.env Variable name.

### ISSUE THREAD

**Issue by ddesir** [yauhofung/MovieSearchEngine#23]
How are we formatting the `.env`. I propose `REACT_APP_API_KEY` or `REACT_APP_MOVIE_API` and to confirm, we're placing it at root, right?

**Comment by yauhofung** [comment]
According to the SearchBar.js file, we're accessing our API key via `this.apiKey = process.env.REACT_APP_API`. So your .env file should contain `REACT_APP_API="<api_key>"` such that `<api_key>` is where you will put your actual TMDb API key.
