### ISSUE TITLE
Cannot read property map type error

### ISSUE THREAD

**Issue by ddesir** [yauhofung/MovieSearchEngine#28]
<img width="534" alt="Screen Shot 2021-01-22 at 6 07 36 PM" src="https://user-images.githubusercontent.com/891705/105558757-4fb93e00-5cdd-11eb-8fa1-62533eba6d68.png">
Here is the message I am getting while trying to redirect my props via home to to the movie list. I converted the components to class components. changed `props.*` to `this.props.*` and still getting the same message.

**Comment by yauhofung** [comment]
If I'm reading your deon-movie-list branch correctly, the order of inheritance is App.js>>Home.js>>MovieList.js. Since Henry declared the movies array in SearchBar.js, your MovieList component cannot access it.

**Comment by yauhofung** [comment]
Wait, why is there a Home component at the bottom of SearchBar.js?
