### ISSUE TITLE
Movie API

### ISSUE THREAD

**Issue by yauhofung** [yauhofung/MovieSearchEngine#3]
Potential API candidate for our movie search engine: https://imdb-api.com/

**Comment by ddesir** [comment]
I was looking at it this morning. I downloaded the documentation, but I have no clue whether it is free or not.

**Comment by Henotis** [comment]
Cat API: 
* https://docs.thecatapi.com/
Public APIs all:
* https://github.com/public-apis/public-apis

**Comment by yauhofung** [comment]
It looks like the Public APIs repository that Henry posted has quite a few movie APIs to choose from.
https://github.com/public-apis/public-apis#video

**Comment by ddesir** [comment]
These seem to be the only Movie search related APIs under video:
http://www.omdbapi.com/
https://www.themoviedb.org/documentation/api
https://trakt.tv/b/api-docs

**Comment by jonathan-chin** [comment]
the imdb database is free for the first 1,000 calls per day
I looked at themoviedb.org and it might actually be the best solution
trakt might be another good resource. however, I can't seem to find pricing for them. themoviedb.org is explicitly free so long as you credit them.

**Comment by Henotis** [comment]
https://www.youtube.com/watch?v=bqSSLr8A8PU
https://www.youtube.com/watch?v=nrJIJuaZsjA
First one is a full website guide for movieDB
Second link is a shorter guide for fetching movieDB API

**Comment by Henotis** [comment]
https://www.youtube.com/watch?v=o-_H6TdXgiU&list=PL_kAgwZgMfWyZ6m8fDwdiwEarr_g6nFxz
The creator of the 2nd youtube link also covers pagination in his movieDB playlist here

**Comment by jonathan-chin** [comment]
hi all, just double checking. have you decided on an api to use? if so, you can comment it and close this issue.

**Comment by ElvisRodriguez** [comment]
Just to give my 2 cents, I used OMDB api and got around the 1000 daily request limit by caching the requests. So the api would only be called for movies that the application has not yet saved.

Alternatively, if there isn't enough time to build a backend DB to cache data, their lowest tier patreon is only $1 and allows 100,000 daily requests.

**Comment by yauhofung** [comment]
Since [The Movie Database (TMDb)](https://www.themoviedb.org/documentation/api) has plenty of videos demonstrating its usage, we will use it for the capstone project moving forward.
