### ISSUE TITLE
Can someone fix the grids for displaying the movies when using the search bar in advanced search?

### ISSUE THREAD

**Issue by Henotis** [yauhofung/MovieSearchEngine#30]
I made a duplicate of the navbar search bar into the advanced search and it works just fine, however, the grid spacing need work so that it displays the movies horizontally.

**Comment by yauhofung** [comment]
I'm taking a look now.

**Comment by Henotis** [comment]
The files that you'll have to edit are in MovieList.js, MoviePage.js, and Pagination for the numbers are the bottom.

**Comment by yauhofung** [comment]
I fixed the warnings from the terminal and browser console, but the search result cards aren't displaying horizontally for some reason. I'll keep testing.

**Comment by yauhofung** [comment]
The search results on the advanced search page now display correctly.
I will see if I can do the same for the pagination at the bottom.

**Comment by yauhofung** [comment]
Update: Kris has volunteered to look into the issue with the pagination.

**Comment by yauhofung** [comment]
I went ahead and merged Henry's branch into main.
