### ISSUE TITLE
Project Outline

### ISSUE THREAD

**Issue by yauhofung** [yauhofung/MovieSearchEngine#4]
I got us started on the capstone outline for assignment eleven, but it still needs pseudocode for the implementation and a graphical outline.

To help divide the workload, I suggest @Henotis and @ddesir work on finishing the outline while @SuperArtisMickens creates and uploads the MS Paint layout.

Feel free to use this issue for questions and comments.

**Comment by Henotis** [comment]
#5

**Comment by yauhofung** [comment]
Kris has submitted the GitHub link to assignment eleven.
