### ISSUE TITLE
Pagination Component Inline

### ISSUE THREAD

**Issue by ddesir** [yauhofung/MovieSearchEngine#49]
Arrows should be made inline with the rest of the page list.
<img width="257" alt="Screen Shot 2021-01-27 at 11 11 51 AM" src="https://user-images.githubusercontent.com/891705/106019275-776b2600-6090-11eb-9826-53a50d897738.png">

**Comment by SuperArtisMickens** [comment]
Done, , , ,

**Comment by SuperArtisMickens** [comment]
Manner of manipulating the grid container....
